import express from 'express';
import dotenv from 'dotenv';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, '../../.env') });

const router = express.Router();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const systemPrompt = `You are AI LegalGPT, an Indian legal assistant.
Answer legal questions clearly.
If the user question is in Tamil, answer in Tamil.
If the user question is in English, answer in English.
Do not mention datasets or training data.
Provide simple explanations suitable for the general public.`;

// POST /api/chat
router.post('/', async (req, res) => {
  try {
    const { query } = req.body;
    
    if (!query) {
      return res.status(400).json({ error: 'Query is required' });
    }
    
    console.log(`Processing AI LegalGPT request: ${query}`);
    
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const fullPrompt = `${systemPrompt}\n\nUser Question:\n${query}`;
    
    const result = await model.generateContent(fullPrompt);
    const response = await result.response;
    const answer = response.text();

    res.json({
      answer,
      citations: [], // No longer using local RAG, so citations are empty or generated by AI
      section_title: "",
      confidence: 1.0
    });
  } catch (error) {
    console.error('Chat error:', error);
    res.status(500).json({ 
      error: "Failed to get response from AI LegalGPT",
      details: error.message
    });
  }
});

/**
 * Handle WebSocket chat events
 */
export const setupSocketHandlers = (io) => {
  io.on('connection', (socket) => {
    console.log('Client connected:', socket.id);
    
    socket.on('chat:message', async (data) => {
      const { query } = data;
      
      try {
        socket.emit('chat:typing', { isTyping: true });
        
        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const fullPrompt = `${systemPrompt}\n\nUser Question:\n${query}`;
        
        const result = await model.generateContent(fullPrompt);
        const response = await result.response;
        const answer = response.text();
        
        socket.emit('chat:complete', {
          answer,
          citations: [],
          section_title: "",
          confidence: 1.0,
        });
        
        socket.emit('chat:typing', { isTyping: false });
        
      } catch (error) {
        console.error('Socket chat error:', error);
        socket.emit('chat:error', { 
          error: error.message || 'Failed to process request',
          details: error.response?.data?.error || null
        });
        socket.emit('chat:typing', { isTyping: false });
      }
    });
    
    socket.on('disconnect', () => {
      console.log('Client disconnected:', socket.id);
    });
  });
};

export default router;
